### ISSUE TITLE
Playtime

### ISSUE THREAD

**Issue by gpotter2** [CodeLanx/PlayTime#58]
This is not a issue, but as the MP were removed...

Just to know: Is this project still alive ?

**Comment by 1Rogue** [comment]
Working on a different release, which is what's really taking up my own time. For now, I have a port of the plugin to a new library (of my own), and once my other release is done I can work on Playtime. It's next on my priority after a couple of paid projects, right next to another plugin (Plotted)

**Comment by gpotter2** [comment]
Hey !

So... it would be in a long time ?

**Comment by 1Rogue** [comment]
Not too long, the release of what I'm working on should be okay as of this week, then I can continue here.

**Comment by gpotter2** [comment]
anyway, if you want it, i adapted the code you made to make it work on 1.8.6..

Thanks for the update
