### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by Quintoking** [CodeLanx/PlayTime#59]
Permissions do not work?! I've added the correct one and the commands only let me use them on ops

```
- playtime.use
```

is there something else? like no one can do it even with other perms. using the most updated version and im running bukkit 1.8.7

**Comment by Quintoking** [comment]
.... anyone can help or?

**Comment by 1Rogue** [comment]
Please paste your entire permissions.yml, the permissions do work, it's very likely that you have groups or permissions assigned incorrectly as a whole.

**Comment by Quintoking** [comment]
Every other permssion is correct and works for all other plugins here is the guest rank just some permssions that all work besides playtime ones
permissions:
    - playtime.use.top
    - dungeonbuilder.dungeons.start
    - magicspells.rank.Novice
    - playtime.use
    - noitem.nocraft.woodensword
    - keepitems.keepxp
    - keepitems.keep

**Comment by 1Rogue** [comment]
Please, provide the full file. That alone provides no context.
